### ISSUE TITLE
Failed to pack sql to nxd

### ISSUE THREAD

**Issue by ggdog007** [Nenkai/FF16Tools#18]
Hi,
Thanks for the quick release of the new version.
But with new version, I encountered an error when packing sql database into nxd file. Error message is 

```
[00:08:59] [Fatal] Unable to import from SQLite System.IO.InvalidDataException: Column 'AccessHoldParamId' for table 'access' does not exist in sqlite table
   at FF16Tools.Files.Nex.Exporters.SQLiteToNexImporter.FillTables() in C:\Users\nenkai\source\repos\FF16Unpacker\FF16Tools.Files\Nex\Importers\SQLiteToNexImporter.cs:line 131
   at FF16Tools.Files.Nex.Exporters.SQLiteToNexImporter.ReadSqlite() in C:\Users\nenkai\source\repos\FF16Unpacker\FF16Tools.Files\Nex\Importers\SQLiteToNexImporter.cs:line 56
   at FF16Tools.CLI.Program.SqliteToNxd(SqliteToNxdVerbs verbs) in C:\Users\nenkai\source\repos\FF16Unpacker\FF16Tools.CLI\Program.cs:line 420
```

It seems it is due to similar error before that it is refering your windows username "C:\Users\nenkai"

Thanks,

**Comment by ggdog007** [comment]
And for example if I try to pack "euipitem" table into nxd, it returns an error:

```
[09:42:01] [Fatal] Unable to import from SQLite System.IO.InvalidDataException: Column 'DLCFlags' for table 'equipitem' does not exist in sqlite table
   at FF16Tools.Files.Nex.Exporters.SQLiteToNexImporter.FillTables() in C:\Users\nenkai\source\repos\FF16Unpacker\FF16Tools.Files\Nex\Importers\SQLiteToNexImporter.cs:line 131
   at FF16Tools.Files.Nex.Exporters.SQLiteToNexImporter.ReadSqlite() in C:\Users\nenkai\source\repos\FF16Unpacker\FF16Tools.Files\Nex\Importers\SQLiteToNexImporter.cs:line 56
   at FF16Tools.CLI.Program.SqliteToNxd(SqliteToNxdVerbs verbs) in C:\Users\nenkai\source\repos\FF16Unpacker\FF16Tools.CLI\Program.cs:line 420
```
Would you please help on this?
Thanks,

**Comment by ggdog007** [comment]
My apology. It seems after using latest tool release, and unpack the nxd.
The error is gone. 
This ticket can be closed.

**Comment by ggdog007** [comment]
problem solved by latest release
